version: "3"
services:
  burni-firely-validator:
    build: ./
    container_name: burni-firely-validator
    ports:
      - "7414:7414"
    networks:
      extnetwork:
        ipv4_address: 172.28.0.17
    restart: always
    
networks:
  extnetwork:
    ipam:
      config:
        - subnet: 172.28.0.0/16    
  
