version: "3"
services:
  fhir-validator-api:
    build: ./
    image: fhir-validator-api
    container_name: fhir-validator-api
    ports:
      - "7414:7414"
    networks:
      extnetwork:
        ipv4_address: 172.28.0.17
    restart: always
    
networks:
  extnetwork:
    ipam:
      config:
        - subnet: 172.28.0.0/16    
  
